spring.application.name=PRODUCT-SERVICE
server.port=8092


# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:}
spring.rabbitmq.port=${RABBITMQ_PORT:}
spring.rabbitmq.virtual-host=${RABBITMQ_USERNAME:}
spring.rabbitmq.username=${RABBITMQ_USERNAME:}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:}

app.rabbitmq.prefix=${RABBITMQ_PREFIX:developer}

#Swagger
springdoc.api-docs.path=/api/products/v3/api-docs

#Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api_key=${CLOUDINAY_API_KEY:}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:}